import test from 'node:test';
import assert from 'node:assert/strict';
import { createEngine } from '../server/engine.mjs';
import { createDemoController } from '../src/demo-controller.mjs';
test('Offline-Vorführung: Scan, Sperre, Vorspulen, Rückgabe, Pause und Reset', async () => {
  const d = createDemoController(await createEngine(), () => 100000);
  d.send({ type: 'confirm' });
  assert.equal(d.state().signal.green, true);
  d.send({ type: 'tap', uid: 'sim:K01' });
  assert.equal(d.state().rooms.K.occupied, 1);
  assert.equal(d.send({ type: 'tap', uid: 'sim:K01' }).ok, false);
  d.send({ type: 'advance', seconds: 10 });
  d.send({ type: 'tap', uid: 'sim:K01' });
  assert.equal(d.state().rooms.K.occupied, 0);
  d.send({ type: 'pause', paused: true });
  assert.equal(d.state().signal.green, false);
  d.send({ type: 'demoReset' });
  assert.equal(d.state().ready, false);
  assert.equal(d.state().rooms.K.free, 48);
  assert.equal(d.state().rooms.M.open, false);
});
test('Offline-Vorführung: gehaltene Karte, Fehlerrollback und Unterbrechung', async () => {
  let now = 100000;
  const d = createDemoController(await createEngine(), () => now);
  d.send({ type: 'confirm' });
  d.send({ type: 'scan', uid: 'sim:K01' });
  d.send({ type: 'advance', seconds: 60 });
  assert.equal(d.send({ type: 'scan', uid: 'sim:K01' }).ok, false);
  assert.equal(d.state().rooms.K.occupied, 1);
  d.send({ type: 'remove' });
  d.send({ type: 'storageFailure', enabled: true });
  assert.equal(d.send({ type: 'tap', uid: 'sim:K02' }).ok, false);
  assert.equal(d.state().rooms.K.occupied, 1);
  d.send({ type: 'storageFailure', enabled: false });
  d.send({ type: 'tap', uid: 'sim:K02' });
  assert.equal(d.state().rooms.K.occupied, 2);
  d.send({ type: 'disconnect' });
  assert.equal(d.online(), false);
  assert.equal(d.send({ type: 'tap', uid: 'sim:K03' }).ok, false);
  now += 8000;
  assert.equal(d.online(), true);
  d.send({ type: 'restart' });
  assert.equal(d.state().rooms.K.occupied, 2);
  assert.equal(d.state().ready, false);
});
