"""Builds the Dial's smooth font (Inter, SIL OFL) as 4-bit alpha glyphs in four sizes, plus an integer sine table.

Writes the same data twice so that the Dial and the browser paint identical pixels:
  core/dial_font.hpp  (const arrays in flash, used by core/dial_raster.hpp and for text measurement)
  src/dial-font.mjs   (used by src/dial-paint.mjs: simulation, help tab, printed guide)
Run: python3 scripts/build-dial-font.py
"""
from pathlib import Path
import base64, math
from PIL import ImageFont

root = Path(__file__).resolve().parent.parent
fonts = root / 'vendor/fonts'
text_chars = ''.join(chr(c) for c in range(0x20, 0x7F)) + 'ÄÖÜäöüß·–…„“”°'
upper_chars = ' 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ-:!?.,·/'
# size: (file, pixel size, characters). Size 1 = small text, 2 = main lines, 3 = status, 4 = big numbers.
sizes = [
    ('Inter-SemiBold.ttf', 15, text_chars),
    ('Inter-Bold.ttf', 20, text_chars),
    ('Inter-Bold.ttf', 27, upper_chars),
    ('Inter-Bold.ttf', 52, upper_chars),
]
data = bytearray()
fontinfo, glyphs = [], []
for file, px, chars in sizes:
    font = ImageFont.truetype(str(fonts / file), px)
    cap = -font.getbbox('H', anchor='ls')[1]
    first = len(glyphs)
    for ch in sorted(set(chars)):
        mask, (ox, oy) = font.getmask2(ch, mode='L', anchor='ls')
        w, h = mask.size
        adv = round(font.getlength(ch))
        offset = len(data)
        nibbles = [(mask.getpixel((x, y)) * 15 + 127) // 255 for y in range(h) for x in range(w)]
        if len(nibbles) % 2:
            nibbles.append(0)
        for i in range(0, len(nibbles), 2):
            data.append(nibbles[i] << 4 | nibbles[i + 1])
        glyphs.append((ord(ch), adv, w, h, ox, oy, offset))
    fontinfo.append((first, len(glyphs) - first, cap, px))
sine = [round(math.sin(math.radians(d)) * 16384) for d in range(360)]

hpp = ['// Generated by scripts/build-dial-font.py from Inter (SIL Open Font License, licenses/Inter.txt). Do not edit.',
       '#pragma once', '#include <cstdint>', 'namespace mensa::font {',
       'struct Glyph {', '  uint16_t code;', '  uint8_t advance, w, h;', '  int8_t x, y;', '  uint32_t offset;', '};',
       'struct Face {', '  uint16_t first, count;', '  uint8_t cap, px;', '};',
       f'inline constexpr Face faces[{len(fontinfo)}] = {{' + ', '.join('{%d, %d, %d, %d}' % f for f in fontinfo) + '};',
       f'inline constexpr Glyph glyphs[{len(glyphs)}] = {{']
for g in glyphs:
    hpp.append('    {%d, %d, %d, %d, %d, %d, %d},' % g)
hpp.append('};')
hpp.append(f'inline constexpr uint8_t alpha[{len(data)}] = {{')
for i in range(0, len(data), 24):
    hpp.append('    ' + ', '.join(str(b) for b in data[i:i + 24]) + ',')
hpp.append('};')
hpp.append('// sin(degrees) * 16384, for the ring and its round ends (same table in the browser).')
hpp.append('inline constexpr int16_t sine[360] = {' + ', '.join(map(str, sine)) + '};')
hpp.append('} // namespace mensa::font')
(root / 'core/dial_font.hpp').write_text('\n'.join(hpp) + '\n', encoding='utf-8')

flat = [v for g in glyphs for v in g]
mjs = ['// Generated by scripts/build-dial-font.py from Inter (SIL Open Font License, licenses/Inter.txt). Do not edit.',
       'export const faces = ' + str([list(f) for f in fontinfo]) + ';',
       '// code, advance, w, h, x, y, offset per glyph',
       'export const glyphs = ' + str(flat) + ';',
       "export const alpha = Uint8Array.from(atob('" + base64.b64encode(bytes(data)).decode() + "'), c => c.charCodeAt(0));",
       'export const sine = ' + str(sine) + ';']
(root / 'src/dial-font.mjs').write_text('\n'.join(mjs) + '\n', encoding='utf-8')
print(f'{len(glyphs)} Glyphen, {len(data) // 1024} KB Alphawerte')
