"""Builds firmware/src/ca_bundle.h: the root certificates the Dial trusts for the online update (0.25), in the format of
the ESP32 certificate bundle (WiFiClientSecure::setCACertBundle, esp_crt_bundle.c):
  2 bytes number of certificates, then per certificate: 2 bytes subject length, 2 bytes key length, subject (DER),
  public key (SubjectPublicKeyInfo, DER); sorted by subject (the library searches it binary).
Source: Mozilla's root list as shipped by the Python package certifi (not the system store, which may contain proxy
certificates). Only the large public CAs that GitHub and its download servers use, so the bundle stays small.
Run: python3 scripts/build-ca-bundle.py [path/to/cacert.pem]
"""
import sys
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import serialization

root = Path(__file__).resolve().parent.parent
if len(sys.argv) > 1:
    source = Path(sys.argv[1])
else:
    import certifi

    source = Path(certifi.where())
owners = (
    'DigiCert Inc',
    'The USERTRUST Network',
    'Sectigo Limited',
    'Comodo CA Limited',
    'Internet Security Research Group',
    'GlobalSign',
    'GlobalSign nv-sa',
    'Google Trust Services LLC',
    'Amazon',
    'Microsoft Corporation',
)
certs = x509.load_pem_x509_certificates(source.read_bytes())
picked = {}
for c in certs:
    org = [a.value for a in c.subject.get_attributes_for_oid(x509.NameOID.ORGANIZATION_NAME)]
    if not org or org[0] not in owners:
        continue
    name = c.subject.public_bytes()
    key = c.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    picked[name] = (key, c.subject.rfc4514_string())
data = bytearray(len(picked).to_bytes(2, 'big'))
for name in sorted(picked):
    key, _ = picked[name]
    data += len(name).to_bytes(2, 'big') + len(key).to_bytes(2, 'big') + name + key
lines = [
    '#pragma once',
    '// Generated by scripts/build-ca-bundle.py from Mozilla\'s root list (certifi). Do not edit.',
    f'// {len(picked)} root certificates for the online update (GitHub and its download servers):',
]
lines += [f'//   {subject}' for _, subject in sorted(picked.values(), key=lambda v: v[1])]
lines += ['#include <cstdint>', f'static const uint8_t caBundle[{len(data)}] = {{']
for i in range(0, len(data), 24):
    lines.append('    ' + ', '.join(f'0x{b:02x}' for b in data[i : i + 24]) + ',')
lines += ['};', '']
(root / 'firmware/src/ca_bundle.h').write_text('\n'.join(lines))
print(f'{len(picked)} Zertifikate, {len(data)} Bytes')
