import { useEffect, useRef } from 'react';
import { paintDial, dialSize } from './dial-paint.mjs';
import guide from './dial-screens.json';
import type { DialItem } from './types';
// Operating help for the Dial with the same screens as the printed guide (generated by scripts/build-dial-guide.mjs).
type Screen = { id: string; title: string; meaning: string; action: string; items: DialItem[] };
const screens = guide.screens as Screen[],
  handgriffe = guide.handgriffe as [string, string, string][];
function DialPicture({ id, small = false }: { id: string; small?: boolean }) {
  const ref = useRef<HTMLCanvasElement>(null),
    screen = screens.find(s => s.id === id)!;
  useEffect(() => {
    const ctx = ref.current?.getContext('2d');
    if (ctx) ctx.putImageData(new ImageData(paintDial(screen.items), dialSize, dialSize), 0, 0);
  }, [screen]);
  return (
    <canvas
      ref={ref}
      width={dialSize}
      height={dialSize}
      className={`help-dial ${small ? 'small' : ''}`}
      role="img"
      aria-label={`Dial-Bildschirm: ${screen.title}`}
    />
  );
}
export function Help() {
  return (
    <>
      <div className="intro">
        <div>
          <h1>Bedienung am Dial</h1>
          <p>
            Für alle, die in der Mensa Dienst haben. Das Dial steht drinnen, das Tablet vor der Tür ist nur die Ampel.
          </p>
        </div>
      </div>
      <section className="flow-section help-section">
        <h2>Die fünf Handgriffe</h2>
        <div className="help-list">
          {handgriffe.map(([when, id, what]) => (
            <div className="help-row" key={id}>
              <DialPicture id={id} small />
              <div>
                <strong>{when}</strong>
                <p className="help-do">{what}</p>
              </div>
            </div>
          ))}
        </div>
      </section>
      <section className="flow-section help-section">
        <h2>Taste, Ring und Fläche</h2>
        <div className="table-scroll">
          <table>
            <tbody>
              <tr>
                <th>Taste kurz drücken</th>
                <td>
                  Grün: Pause · Pause/Entlastung: weiter · Countdown: nächste Gruppe sofort · Mensa-Einstellung:
                  übernehmen
                </td>
              </tr>
              <tr>
                <th>Taste 3 s halten</th>
                <td>
                  Weißer Ring zeigt den Fortschritt. Bestand unbestätigt: Bestand bestätigen · „Neuer Tag?“: neuen
                  Essenstag starten · sonst: WLAN-Daten anzeigen
                </td>
              </tr>
              <tr>
                <th>Taste 10 s halten</th>
                <td>Zugang zurücksetzen (nur bei vergessenem Kennwort, zur Bestätigung nochmal 3 s halten)</td>
              </tr>
              <tr>
                <th>Ring drehen</th>
                <td>Ab zwei Rasten: Mensaplätze einstellen, Taste übernimmt, 0 = Mensa sperren</td>
              </tr>
              <tr>
                <th>Fläche „ENTLASTEN“</th>
                <td>Einlass sofort stoppen, weil es an der Ausgabe zu voll ist</td>
              </tr>
              <tr>
                <th>Betreuerkarte vorhalten</th>
                <td>Menü mit Bestand ok, Pause/Weiter, Mensa freigeben (Ring = Auswahl, Taste = ausführen)</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="hint">
          Die Taste ist die Front des Dials: den Bildschirm bzw. Drehknopf nach unten drücken. Karten werden direkt am
          Dial vorgehalten.
        </p>
      </section>
      <section className="flow-section help-section">
        <h2>Was zeigt das Dial?</h2>
        <div className="help-grid">
          {screens.map(s => (
            <div className="help-row" key={s.id}>
              <DialPicture id={s.id} small />
              <div>
                <strong>{s.title}</strong>
                <p>{s.meaning}</p>
                <p className="help-do">{s.action}</p>
              </div>
            </div>
          ))}
        </div>
      </section>
      <section className="flow-section help-section">
        <h2>Ablauf an einem Tag</h2>
        <ol>
          <li>
            <strong>Einschalten:</strong> „Bestand ok?“ → Karten kurz prüfen → Taste 3 s halten.
          </li>
          <li>
            <strong>Tablet vor der Tür:</strong> Ampelseite (/ampel) öffnen, Vollbild, optional „Ton an“.
          </li>
          <li>
            <strong>Mittag:</strong> Die erste Gruppe ist größer, danach öffnet die Ampel im Takt von selbst.
          </li>
          <li>
            <strong>Begleitete Kinder fertig:</strong> Ring drehen, Mensaplätze einstellen, Taste.
          </li>
          <li>
            <strong>Nur bei Bedarf:</strong> zu voll → ENTLASTEN; Ausgabe schon frei → Taste.
          </li>
          <li>
            <strong>Ende:</strong> „Karten fehlen“ → Karten einsammeln.
          </li>
        </ol>
        <p className="hint">
          Zum Ausdrucken gibt es die Anleitung und eine Kurzkarte zum Aufkleben im Gerätepaket bzw. auf der
          Release-Seite (BEDIENUNG-DIAL.pdf, DIAL-KURZKARTE.pdf).
        </p>
      </section>
    </>
  );
}
