import React from 'react';import {createRoot} from 'react-dom/client';import {useState} from 'react';import {ExternalLink,X,CheckCircle2,AlertCircle} from 'lucide-react';
import {useMensa} from './useMensa';import {Management} from './Management';import {Simulation} from './Simulation';import {Signal} from './Signal';import './style.css';
import {FlowPanel} from './FlowPanel';
import {Login,DevicePanel} from './DevicePanel';
import {Help} from './Help';
function App(){
 const model=useMensa();const [tab,setTab]=useState(location.hash==='#messungen'?'flow':location.hash==='#simulation'?'simulation':location.hash==='#geraet'?'device':location.hash==='#hilfe'?'help':'management');const device=model.info?.mode==='device';
 if(location.pathname==='/ampel')return <Signal state={model.state} connected={model.connected} full/>;
 return <><header><a href="/" className="brand">Mensaampel</a><nav aria-label="Hauptnavigation"><button className={tab==='management'?'selected':''} onClick={()=>{setTab('management');location.hash='betreuung';}}>Betreuung</button>{device?<button className={tab==='device'?'selected':''} onClick={()=>{setTab('device');location.hash='geraet';}}>Gerät</button>:<button className={tab==='simulation'?'selected':''} onClick={()=>{setTab('simulation');location.hash='simulation';}}>Simulation</button>}<button className={tab==='flow'?'selected':''} onClick={()=>{setTab('flow');location.hash='messungen';}}>Einlass & Messungen</button><button className={tab==='help'?'selected':''} onClick={()=>{setTab('help');location.hash='hilfe';}}>Hilfe</button></nav><a href="/ampel" target="_blank" rel="noreferrer" className="button outline"><ExternalLink size={19}/> Ampel öffnen</a>{device&&!model.authRequired&&model.state&&<button className="quiet" onClick={()=>void model.logout()}>Abmelden</button>}</header>
 <main>{model.authRequired&&model.info?<Login info={model.info} busy={model.busy} authenticate={model.authenticate} error={model.notice?.ok?undefined:model.notice?.text}/>:!model.state?<div className="loading"><h1>Verbindung wird hergestellt</h1><p>{device?'Bitte mit dem WLAN der Mensaampel verbinden.':'Die lokale Mensaampel wird geladen. Falls diese Meldung bleibt, bitte die Startdatei erneut öffnen.'}</p></div>:<>{!model.connected&&<div className="banner error" role="alert"><AlertCircle/><div><strong>Verbindung unterbrochen</strong><p>Die Anzeige wird automatisch wieder verbunden. Bis dahin bleibt die Ampel rot.</p></div></div>}{tab==='help'?<Help/>:device&&(tab==='device'||!model.state.device?.configured)?<DevicePanel {...model} state={model.state}/>:tab==='flow'?<FlowPanel {...model} state={model.state}/>:tab==='management'||device?<Management {...model} state={model.state}/>:<Simulation {...model} state={model.state}/>}</>}</main>
 <footer><span><i className={model.connected?'connected':'disconnected'}/>{model.connected?'Lokal verbunden':'Keine Verbindung'}</span><span>{device?'M5Stack Dial · Lokales WLAN':'PC-Simulation · Keine Verbindung zu echten Karten'}</span><span>Essenstag {model.state?.day||1}</span></footer>
 {model.notice&&<div className={`toast ${model.notice.ok?'success':'failure'}`} role="status">{model.notice.ok?<CheckCircle2/>:<AlertCircle/>}<span>{model.notice.text}</span><button aria-label="Meldung schließen" onClick={()=>model.setNotice(null)}><X size={18}/></button></div>}
 </>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
