[platformio]
default_envs = mensa-dial

[env]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_unflags = -std=gnu++11 -fno-exceptions
build_flags = -std=gnu++17 -fexceptions -DARDUINO_USB_CDC_ON_BOOT=1 -DARDUINO_USB_MODE=1
monitor_speed = 115200

[env:mensa-dial]
build_src_filter = +<*> -<core_check.cpp>
lib_deps =
    m5stack/M5Dial@1.0.3
    m5stack/M5Unified@0.2.23
    m5stack/M5GFX@0.2.30

[env:dial-core-check]
build_src_filter = -<*> +<core_check.cpp>
